import type { Artist } from "./types"

export const artists: Artist[] = [
  {
    id: "1",
    name: "Priya Sharma",
    category: ["Singers"],
    priceRange: "₹15,000 - ₹25,000",
    location: "Mumbai",
    bio: "Classical and Bollywood singer with 8 years of experience. Specializes in wedding ceremonies and corporate events. Trained in Hindustani classical music.",
    languages: ["Hindi", "English", "Marathi"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "2",
    name: "Rahul Mehta",
    category: ["Comedians", "Speakers"],
    priceRange: "₹20,000 - ₹35,000",
    location: "Delhi",
    bio: "Stand-up comedian and motivational speaker. Known for clean comedy and engaging corporate presentations. Featured in multiple comedy shows.",
    languages: ["Hindi", "English", "Punjabi"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "3",
    name: "Anjali Nair",
    category: ["Dancers"],
    priceRange: "₹12,000 - ₹20,000",
    location: "Chennai",
    bio: "Bharatanatyam and contemporary dance performer. Award-winning dancer with performances across South India. Perfect for cultural events.",
    languages: ["Tamil", "English", "Malayalam"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "4",
    name: "DJ Arjun",
    category: ["DJs"],
    priceRange: "₹25,000 - ₹50,000",
    location: "Bangalore",
    bio: "Professional DJ specializing in weddings and corporate parties. Expert in Bollywood, EDM, and regional music. State-of-the-art equipment provided.",
    languages: ["English", "Hindi", "Kannada"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "5",
    name: "Kavya Reddy",
    category: ["Singers", "Musicians"],
    priceRange: "₹10,000 - ₹25,000",
    location: "Hyderabad",
    bio: "Versatile singer and guitarist. Performs acoustic sets, folk music, and contemporary songs. Perfect for intimate gatherings and cafes.",
    languages: ["Telugu", "Hindi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "6",
    name: "Vikram Singh",
    category: ["Speakers"],
    priceRange: "₹50,000 - ₹1,00,000",
    location: "Mumbai",
    bio: "Corporate trainer and keynote speaker. Specializes in leadership, team building, and motivation. Worked with Fortune 500 companies.",
    languages: ["English", "Hindi"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "7",
    name: "Meera Joshi",
    category: ["Dancers"],
    priceRange: "₹8,000 - ₹15,000",
    location: "Pune",
    bio: "Kathak dancer and choreographer. Teaches and performs traditional and fusion dance forms. Great for cultural programs and festivals.",
    languages: ["Hindi", "Marathi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "8",
    name: "Rohit Kumar",
    category: ["Comedians"],
    priceRange: "₹15,000 - ₹30,000",
    location: "Delhi",
    bio: "Hindi and English stand-up comedian. Specializes in observational comedy and crowd interaction. Regular performer at comedy clubs.",
    languages: ["Hindi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "9",
    name: "Shreya Ghosh",
    category: ["Singers"],
    priceRange: "₹12,000 - ₹22,000",
    location: "Kolkata",
    bio: "Bengali and Hindi playback singer. Trained in Rabindra Sangeet and modern music. Perfect for cultural events and private functions.",
    languages: ["Bengali", "Hindi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "10",
    name: "DJ Ravi",
    category: ["DJs"],
    priceRange: "₹18,000 - ₹35,000",
    location: "Ahmedabad",
    bio: "Wedding and party DJ with expertise in Gujarati folk, Bollywood, and international music. Complete sound and lighting setup available.",
    languages: ["Gujarati", "Hindi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "11",
    name: "Aditi Iyer",
    category: ["Dancers", "Singers"],
    priceRange: "₹20,000 - ₹40,000",
    location: "Chennai",
    bio: "Multi-talented performer specializing in Carnatic music and Bharatanatyam. Temple dancer and classical music vocalist with 12 years experience.",
    languages: ["Tamil", "Sanskrit", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    experience: "Expert (10+ years)",
  },
  {
    id: "12",
    name: "Aryan Kapoor",
    category: ["Magicians"],
    priceRange: "₹25,000 - ₹45,000",
    location: "Jaipur",
    bio: "Professional magician and illusionist. Specializes in close-up magic, stage shows, and corporate entertainment. Award-winning performer with international experience.",
    languages: ["Hindi", "English", "Rajasthani"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "13",
    name: "Neha Agarwal",
    category: ["Musicians"],
    priceRange: "₹15,000 - ₹28,000",
    location: "Lucknow",
    bio: "Flautist and music composer. Performs Indian classical, fusion, and contemporary music. Perfect for meditation events and cultural programs.",
    languages: ["Hindi", "English", "Urdu"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "14",
    name: "Karthik Subramanian",
    category: ["Actors", "Speakers"],
    priceRange: "₹30,000 - ₹60,000",
    location: "Bangalore",
    bio: "Theater actor and corporate trainer. Specializes in dramatic presentations, team building workshops, and motivational speaking through storytelling.",
    languages: ["English", "Tamil", "Kannada"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    experience: "Expert (10+ years)",
  },
  {
    id: "15",
    name: "Pooja Malhotra",
    category: ["Singers"],
    priceRange: "₹18,000 - ₹32,000",
    location: "Delhi",
    bio: "Sufi and ghazal singer with a soulful voice. Performs at intimate gatherings, cultural events, and private concerts. Trained under renowned ustads.",
    languages: ["Hindi", "Urdu", "Punjabi", "English"],
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    experience: "Experienced (5-10 years)",
  },
]
