import type { Artist } from "./types"

export const artists: Artist[] = [
  {
    id: "1",
    name: "Priya Sharma",
    category: ["Singers"],
    priceRange: "₹15,000 - ₹25,000",
    location: "Mumbai",
    bio: "Classical and Bollywood singer with 8 years of experience. Specializes in wedding ceremonies and corporate events. Trained in Hindustani classical music.",
    languages: ["Hindi", "English", "Marathi"],
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=300&h=300&fit=crop&crop=face",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "2",
    name: "James Anderson",
    category: ["Comedians", "Speakers"],
    priceRange: "₹35,000 - ₹60,000",
    location: "Bangalore",
    bio: "International stand-up comedian and motivational speaker. Known for clean comedy and engaging corporate presentations. Featured in multiple international comedy shows.",
    languages: ["English", "Hindi"],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face",
    rating: 4.8,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "3",
    name: "Anjali Nair",
    category: ["Dancers"],
    priceRange: "₹12,000 - ₹20,000",
    location: "Chennai",
    bio: "Bharatanatyam and contemporary dance performer. Award-winning dancer with performances across South India. Perfect for cultural events.",
    languages: ["Tamil", "English", "Malayalam"],
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "4",
    name: "Marcus Thompson",
    category: ["DJs"],
    priceRange: "₹40,000 - ₹75,000",
    location: "Goa",
    bio: "International DJ specializing in EDM, house, and techno. Regular performer at beach festivals and luxury resorts. State-of-the-art equipment provided.",
    languages: ["English", "Hindi"],
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "5",
    name: "Kavya Reddy",
    category: ["Singers", "Musicians"],
    priceRange: "₹10,000 - ₹25,000",
    location: "Hyderabad",
    bio: "Versatile singer and guitarist. Performs acoustic sets, folk music, and contemporary songs. Perfect for intimate gatherings and cafes.",
    languages: ["Telugu", "Hindi", "English"],
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face",
    rating: 4.6,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "6",
    name: "Vikram Singh",
    category: ["Speakers"],
    priceRange: "₹50,000 - ₹1,00,000",
    location: "Mumbai",
    bio: "Corporate trainer and keynote speaker. Specializes in leadership, team building, and motivation. Worked with Fortune 500 companies.",
    languages: ["English", "Hindi"],
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face",
    rating: 4.9,
    experience: "Expert (10+ years)",
  },
  {
    id: "7",
    name: "Isabella Rodriguez",
    category: ["Dancers"],
    priceRange: "₹25,000 - ₹45,000",
    location: "Mumbai",
    bio: "Professional salsa and contemporary dance instructor from Spain. Teaches and performs Latin and fusion dance forms. Great for parties and cultural programs.",
    languages: ["English", "Spanish", "Hindi"],
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face",
    rating: 4.5,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "8",
    name: "Rohit Kumar",
    category: ["Comedians"],
    priceRange: "₹15,000 - ₹30,000",
    location: "Delhi",
    bio: "Hindi and English stand-up comedian. Specializes in observational comedy and crowd interaction. Regular performer at comedy clubs.",
    languages: ["Hindi", "English"],
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&h=300&fit=crop&crop=face",
    rating: 4.4,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "9",
    name: "Sophie Chen",
    category: ["Singers"],
    priceRange: "₹30,000 - ₹55,000",
    location: "Bangalore",
    bio: "International jazz and blues singer from Canada. Trained in Western classical and contemporary music. Perfect for upscale events and private concerts.",
    languages: ["English", "Mandarin"],
    image: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=300&h=300&fit=crop&crop=face",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "10",
    name: "Arjun Patel",
    category: ["DJs"],
    priceRange: "₹18,000 - ₹35,000",
    location: "Ahmedabad",
    bio: "Wedding and party DJ with expertise in Gujarati folk, Bollywood, and international music. Complete sound and lighting setup available.",
    languages: ["Gujarati", "Hindi", "English"],
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
    rating: 4.6,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "11",
    name: "Aditi Iyer",
    category: ["Dancers", "Singers"],
    priceRange: "₹20,000 - ₹40,000",
    location: "Chennai",
    bio: "Multi-talented performer specializing in Carnatic music and Bharatanatyam. Temple dancer and classical music vocalist with 12 years experience.",
    languages: ["Tamil", "Sanskrit", "English"],
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300&h=300&fit=crop&crop=face",
    rating: 4.8,
    experience: "Expert (10+ years)",
  },
  {
    id: "12",
    name: "Oliver Williams",
    category: ["Magicians"],
    priceRange: "₹45,000 - ₹80,000",
    location: "Delhi",
    bio: "International magician and illusionist from UK. Specializes in close-up magic, stage shows, and corporate entertainment. Award-winning performer with global experience.",
    languages: ["English", "Hindi"],
    image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=300&h=300&fit=crop&crop=face",
    rating: 4.7,
    experience: "Experienced (5-10 years)",
  },
  {
    id: "13",
    name: "Neha Agarwal",
    category: ["Musicians"],
    priceRange: "₹15,000 - ₹28,000",
    location: "Lucknow",
    bio: "Flautist and music composer. Performs Indian classical, fusion, and contemporary music. Perfect for meditation events and cultural programs.",
    languages: ["Hindi", "English", "Urdu"],
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop&crop=face",
    rating: 4.5,
    experience: "Intermediate (2-5 years)",
  },
  {
    id: "14",
    name: "Alessandro Rossi",
    category: ["Actors", "Speakers"],
    priceRange: "₹50,000 - ₹90,000",
    location: "Mumbai",
    bio: "Italian theater actor and corporate trainer. Specializes in dramatic presentations, team building workshops, and motivational speaking through storytelling.",
    languages: ["English", "Italian", "Hindi"],
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&crop=face",
    rating: 4.6,
    experience: "Expert (10+ years)",
  },
  {
    id: "15",
    name: "Pooja Malhotra",
    category: ["Singers"],
    priceRange: "₹18,000 - ₹32,000",
    location: "Delhi",
    bio: "Sufi and ghazal singer with a soulful voice. Performs at intimate gatherings, cultural events, and private concerts. Trained under renowned ustads.",
    languages: ["Hindi", "Urdu", "Punjabi", "English"],
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop&crop=face",
    rating: 4.8,
    experience: "Experienced (5-10 years)",
  },
]
